language: java

jdk:
  - oraclejdk8

script:
  mvn clean install

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/9574c266f9735a0ea466
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

